### ISSUE TITLE
加入license文件以方便pkg.go.dev采录

### ISSUE THREAD

**Issue by katsusan** [devfeel/dottask#10]
访问 https://pkg.go.dev/github.com/devfeel/dottask?tab=doc 显示如下:
![image](https://user-images.githubusercontent.com/11537821/88460639-3111f000-ced0-11ea-8e2b-3d20de85c104.png)

关于license的检测在: https://pkg.go.dev/license-policy

**Comment by devfeel** [comment]
It is supported in version v0.9.10
